name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make

    - name: Install
      run: make install

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: crc
        path: ./cmd/crc
        retention-days: 5

#    - name: Test
#      run: go test -v ./...
